deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

service:
  spec:
    type: NodePort
    externalTrafficPolicy: Cluster

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    expose:
      default: false
  websecure:
    port: 8443
    exposedPort: 443
    nodePort: 30443
    protocol: TCP
    expose:
      default: true
    http:
      tls:
        enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
