apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: homework
  labels:
    app.kubernetes.io/name: backend
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: app
  DB_USER: app
