apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: homework
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: dz6
data:
  config.js: |
    window.APP_CONFIG = {
        frontendVersion: "v2-tls",
        apiBaseUrl: "/api",
    };
