apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: homework
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: dz6
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dz6.local
      secretName: dz6-external-tls
  rules:
    - host: dz6.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8443
