apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-tls-config
  namespace: homework
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: dz6
data:
  pg_hba.conf: |
    local   all   all                         trust
    hostssl all   all   0.0.0.0/0             scram-sha-256
    hostssl all   all   ::/0                  scram-sha-256
    hostnossl all all   0.0.0.0/0             reject
    hostnossl all all   ::/0                  reject
