apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: homework
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: dz6
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: homework
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: dz6
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: homework
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: dz6
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homework-reader
  namespace: homework
  labels:
    app.kubernetes.io/name: homework-reader
    app.kubernetes.io/part-of: dz6
automountServiceAccountToken: false
