---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: homework
  labels:
    app.kubernetes.io/name: vault-auth
    app.kubernetes.io/part-of: dz6
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: dz6
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
